### ISSUE TITLE
Parsing open-source processor core RIDECORE crashes.

### ISSUE THREAD

**Issue by CrazybinaryLi** [chipsalliance/synlig#2228] opened 2023-12-22 01:34 UTC
The path of project is: https://github.com/upscale-project/generic-sqed-demo/tree/master

Read RTL by yosys .ys script file:
plugin -i systemverilog
read_systemverilog -formal ./ridecore-src-buggy/define.v \
./ridecore-src-buggy/topsim.v \
./ridecore-src-buggy/alloc_issue_ino.v \
./ridecore-src-buggy/search_be.v \
./ridecore-src-buggy/srcsel.v  \
./ridecore-src-buggy/alu_ops.vh \
./ridecore-src-buggy/arf.v \
./ridecore-src-buggy/ram_sync.v \
./ridecore-src-buggy/ram_sync_nolatch.v  \
./ridecore-src-buggy/brimm_gen.v \
./ridecore-src-buggy/constants.vh \
./ridecore-src-buggy/decoder.v \
./ridecore-src-buggy/dmem.v \
./ridecore-src-buggy/exunit_alu.v \
./ridecore-src-buggy/exunit_branch.v \
./ridecore-src-buggy/exunit_ldst.v \
./ridecore-src-buggy/exunit_mul.v \
./ridecore-src-buggy/imem.v \
./ridecore-src-buggy/imm_gen.v \
./ridecore-src-buggy/pipeline_if.v \
./ridecore-src-buggy/gshare.v \
./ridecore-src-buggy/pipeline.v \
./ridecore-src-buggy/oldest_finder.v \
./ridecore-src-buggy/btb.v \
./ridecore-src-buggy/prioenc.v \
./ridecore-src-buggy/mpft.v \
./ridecore-src-buggy/reorderbuf.v \
./ridecore-src-buggy/rrf_freelistmanager.v \
./ridecore-src-buggy/rrf.v \
./ridecore-src-buggy/rs_alu.v \
./ridecore-src-buggy/rs_branch.v \
./ridecore-src-buggy/rs_ldst.v \
./ridecore-src-buggy/rs_mul.v \
./ridecore-src-buggy/rs_reqgen.v \
./ridecore-src-buggy/rv32_opcodes.vh \
./ridecore-src-buggy/src_manager.v \
./ridecore-src-buggy/srcopr_manager.v \
./ridecore-src-buggy/storebuf.v \
./ridecore-src-buggy/tag_generator.v \
./ridecore-src-buggy/dualport_ram.v \
./ridecore-src-buggy/alu.v \
./ridecore-src-buggy/multiplier.v \
./sqed-generator/SQED-Generator/QEDFiles/inst_constraints.v \
./sqed-generator/SQED-Generator/QEDFiles/modify_instruction.v \
./sqed-generator/SQED-Generator/QEDFiles/qed_decoder.v \
./sqed-generator/SQED-Generator/QEDFiles/qed_i_cache.v \
./sqed-generator/SQED-Generator/QEDFiles/qed_instruction_mux.v \
./sqed-generator/SQED-Generator/QEDFiles/qed.v;

prep -top top;

hierarchy -check;

chformal -assume -early;

memory;

flatten;

sim -clock clk -resetn reset_x -n 5 -rstlen 5 -zinit -w top

setundef -undriven -expose;

write_btor ridecore.btor2

**Comment by alaindargelas** [comment] 2023-12-22 07:10
Please add here the complete yosys .ys script file.

**Comment by alaindargelas** [comment] 2023-12-26 10:27
The file FV/property.sv does not exist in the repo. Please attach it.
Also, the project file does not correspond to the actual repo, it looks like the project you attached is for a hard copy of the project with modified directory structure....

**Comment by CrazybinaryLi** [comment] 2023-12-26 11:26
Yes, I pulled the RIDECORE project into my local directory and wrote another file locally that contains SystemVerilog assertions. You can try downloading RIDECORE and writing an SVA to check if synlig can parse it.

**Comment by alain-rs** [comment] 2023-12-26 11:39
Please provide a file, even a simple one, else no one will take a look at this issue.
Generally you have to provide simple and accurate instructions to reproduce an issue, else it won't be worked on.

**Comment by CrazybinaryLi** [comment] 2023-12-26 12:44
I have updated the script file.

**Comment by alaindargelas** [comment] 2023-12-27 13:36
Fixed in https://github.com/chipsalliance/synlig/pull/2236

**Closed by alaindargelas** 2023-12-27 13:36 UTC

**Comment by CrazybinaryLi** [comment] 2023-12-30 11:53
This issue has not been fully resolved! The crash is caused by the excessive use of physical memory when using the "plugin -i systemverilog" in the .ys script. Insufficient memory leads to the crash. Currently, this problem still persists.

**Comment by alain-rs** [comment] 2023-12-30 16:31
You probably didn't check out the branch correctly.
Anyhow since I closed the issue,  the main branch has been updated.
Checkout a clean clone from scratch that should fix your local issue
